# search hidden files
hidden = false

# respect .gitignore files
gitignore = true

# use colored output (when the output is a terminal)
color = "auto"

# set the maximum search depth
# max-depth = 3

# follow symbolic links by default
follow = true

# use regular expressions for pattern matching
regex = true

# smart case by default
ignore-case = true

# exclude specific patterns globally
exclude = [
  ".git",
  ".svn",
  "node_modules",
  ".cache",
  ".npm",
  ".mypy_cache",
  "__pycache__",
]
